controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Campus:
    resource: Controller\CampusController
    type: annotation

Outing:
    resource: Controller\OutingController
    type: annotation

Users:
    resource: Controller\UserController
    type: annotation